package com.regiao.view;

import com.regiao.model.AreaCobertura;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;

@SuppressWarnings("serial")
public class AreaView extends Panel {

	public AbsoluteLayout absoluteLayoutArea;
	public Button buttonRemove;
	public TextField textFieldArea;
	private AreaCobertura areaCobertura;
	
	public AreaView(AreaCobertura areaCobertura) {
	    this.areaCobertura = areaCobertura;
	    
		setImmediate(false);
		setWidth("36.0em");
		setHeight("60px");
		
		// absoluteLayoutArea
		absoluteLayoutArea = buildAbsoluteLayoutArea();
		setContent(absoluteLayoutArea);
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayoutArea() {
		// common part: create layout
		absoluteLayoutArea = new AbsoluteLayout();
		absoluteLayoutArea.setImmediate(false);
		absoluteLayoutArea.setWidth("100.0%");
		absoluteLayoutArea.setHeight("100.0%");
		absoluteLayoutArea.setMargin(false);
		
		// textFieldArea
		textFieldArea = new TextField();
		textFieldArea.setImmediate(false);
		textFieldArea.setWidth("350px");
		textFieldArea.setHeight("-1px");
		textFieldArea.setValue(this.areaCobertura.getNome());
		absoluteLayoutArea.addComponent(textFieldArea, "top:15.0px;left:19.0px;");
		
		// buttonRemove
		buttonRemove = new Button("-");
		buttonRemove.setImmediate(false);
		buttonRemove.setData(this);
		buttonRemove.setWidth("-1px");
		buttonRemove.setHeight("-1px");
		absoluteLayoutArea.addComponent(buttonRemove, "top:13.0px;left:380.0px;");
		
		return absoluteLayoutArea;
	}

	public AreaCobertura getAreaCobertura() {
		areaCobertura.setNome(textFieldArea.getValue().toString());
		return areaCobertura;
	}

	public void setAreaCobertura(AreaCobertura areaCobertura) {
		this.areaCobertura = areaCobertura;
	}
}
