package com.view.componente;

import java.util.HashSet;
import com.vaadin.event.Action;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.AbstractTextField.TextChangeEventMode;

@SuppressWarnings({"serial", "unused"})
public class TabelaFiltro extends Panel  {

	  HashSet<Object> markedRows = new HashSet<Object>();

	private static final Action REMOVE_ITEM_ACTION = new Action("Remove");    
	private VerticalLayout mainLayout;
	public  Table tableMain;
	public  TextField filterField;
 	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	public TabelaFiltro(String nomeCaption) {
		
	    setCaption(nomeCaption);
		setWidth("100.0%");
		setHeight("100.0%");
	    addComponent(buildMainLayout());
	}

	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		
		filterField = new TextField();
		filterField.setCaption("Filtro");
	    filterField.setTextChangeEventMode(TextChangeEventMode.LAZY);
	    filterField.setTextChangeTimeout(200);
	    filterField.setWidth("200px");
	    filterField.setHeight("-1px");
		mainLayout.addComponent(filterField);
		mainLayout.setExpandRatio(filterField, 1.0f);
		mainLayout.setComponentAlignment(filterField, new Alignment(34));
		
		// tableMain
		tableMain = new Table();
    	tableMain.setWidth("100.0%");
		tableMain.setHeight("100.0%");
		tableMain.setSelectable(true);
	    tableMain.setColumnReorderingAllowed(true);
	    tableMain.setColumnCollapsingAllowed(true);

		
		mainLayout.addComponent(tableMain);
        
	    
	     
		return mainLayout;

	
	}
}
